### ISSUE TITLE
Tensor mismatch is occuring in eap attribute function for all models except GPT2s.

### ISSUE THREAD

**Issue by zubair2004** [hannamw/EAP-IG#7]
Since this issue was raised earlier and you suggested to downgrade tranformerlens to earlier version=1.12.0, but that doesn't work. Also the newer version 2.0.0 doesn't work either. So, we were working on llama and if we disable the 'BOS' token in llama tokenizer, the issue gets resolved.
###
from transformers import LlamaForCausalLM, LlamaTokenizerFast
model_name = 'meta-llama/Llama-2-7b-hf'
tokenizer = LlamaTokenizerFast.from_pretrained(model_name)
tokenizer.add_bos_token = False
hf_model = LlamaForCausalLM.from_pretrained(model_name).to('cpu')
model = HookedTransformer.from_pretrained(
    model_name, 
    hf_model=hf_model, 
    device='cpu',
    tokenizer=tokenizer
)
model = model.to('cuda')
model.cfg.use_attn_in = True
model.cfg.use_split_qkv_input = True
model.cfg.use_attn_result = True
model.cfg.use_hook_mlp_in = True
###

Also in the evaluate_graph function, if we are using clean and corrupted sentences of different length (unlike your Greater-than task case where the lengths are equal), then while tokenizing the sentence, we have to set add_special_tokens to false.
###
for sentence, corrupted in tqdm(dataset):
        sens = [sentence, corrupted]
        sens = [str(s) for s in sens]
        max_length = max(len(model.tokenizer.tokenize(s, add_special_tokens=False)) for s in sens)
        padded_sentences = [model.tokenizer.encode(s, padding='max_length', max_length=max_length, return_tensors='pt', add_special_tokens=False) for s in sens]
###

I hope you do it in a better way than the mess i have created!

**Comment by hannamw** [comment]
Hi Zubair!

The tokenization issue you're referring to from the other issue was solved
when I updated this repo; please use the versions specified in the
`environment.yml` file.

As for the issues you're encountering—have you tried the
`greater_than.ipynb` notebook with other models, and have you encountered
errors there? It looks like you're doing your own tokenization, but my code
does its own tokenization in a rather specific way, due to these tricky
issues you're encountering. For more details, see `tokenize_plus` in
`attribute.py`. Basically, unless you format the inputs as shown in the
example notebook, the code won't work; you shouldn't pre-tokenize your
input.

Finally, about sentence length: note that while not all the clean sentences
need to have the same length, each (clean, corrupted) pair must; this is a
requirement of circuits more generally, and not this codebase.

Let me know if you have any problems when using the format from the
notebook!

**Comment by zubair2004** [comment]
Hi Michael!
Thank you for your instant feedback. I tried to load pythia-1b in the original greater-than notebook and updating the versions as specified in the `environment.yml` file, but the issue is still the same. here is the notebook where i have loaded this pythia model, i have given the editor access, please feel free to do any changes as you see fit.
https://colab.research.google.com/drive/1OtHhHPtrMHJhGAlN-oBSWCnFcUGuNMhj?usp=sharing
and here are some screenshots of the issue:
![Screenshot 2024-08-25 124918](https://github.com/user-attachments/assets/cb2c7c6f-0bfb-4e38-a5e2-917e19e115f1)

**Comment by hannamw** [comment]
Hi Zubair,

It looks like the `greater_than.ipynb` notebook and data that you're using aren't from the `main` branch; you're using a notebook from the `tutorial` branch. As a result, you're also not using the main / updated version of this repo where all of the problems you've mentioned have been fixed! Can you use the notebook on the main branch? 

I have updated the `requirements.txt` file to make this repo easier to install via Colab. I'd suggest adding the following lines of code to the notebook:

```
!apt install -y graphviz
!apt install libgraphviz-dev
!git clone https://github.com/hannamw/EAP-IG.git
%cd EAP-IG
%pip install -r requirements.txt
%pip install -e .
```

I have tested this myself, and I no longer get the errors you mentioned. However, this repo wasn't really developed for Colab, so it complains about some of the packages that I install. In particular, you may be able to remove the ipykernel/ipython/ipywidgets lines from the requirements file, which will make Colab complain less.

**Comment by zubair2004** [comment]
Hi Michael,
Thank you very much for your assistance. From now on i am going to use the notebook from the main branch.
